# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-05 12:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_auto_20170404_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_spot', to='coffee.Spot'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='commit_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spot',
            name='download_speed',
            field=models.CharField(blank=True, default='', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='speed_test_link',
            field=models.URLField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='upload_speed',
            field=models.CharField(blank=True, default='', max_length=70, null=True),
        ),
    ]
