# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffice', '0002_auto_20170429_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='city',
            field=models.CharField(default='北京', max_length=70),
            preserve_default=False,
        ),
    ]
