# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffice', '0004_auto_20170516_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffice.Spot'),
        ),
    ]
