# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffice', '0005_auto_20170516_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_message',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='commit_message',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
