# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffice', '0006_auto_20170526_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='city_pinyin',
            field=models.CharField(default='beijing', max_length=70),
            preserve_default=False,
        ),
    ]
