# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 05:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffice', '0007_spot_city_pinyin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='city_pinyin',
        ),
    ]
