# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170501_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='open_mark',
            field=models.BooleanField(default=True),
        ),
    ]
