# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_open_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weixin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
