# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_weixin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='client_mark',
            field=models.CharField(blank=True, default='weixin', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='weixin',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
